select ss_sales_price from web_sales, store_sales where ws_item_sk=ss_item_sk and store_sales.ss_ext_sales_price < 470.64 and web_sales.ws_ext_sales_price = 4853.80;
select ws_order_number from web_sales, date_dim where d_date_sk=ws_sold_date_sk and web_sales.ws_list_price < 94.77 and web_sales.ws_wholesale_cost > 9.52;
select ss_net_profit from store_returns, store_sales where ss_ticket_number=sr_ticket_number and store_sales.ss_promo_sk < 224 and store_returns.sr_fee > 93.35;
select ss_addr_sk from item, store_sales where i_item_sk=ss_item_sk and store_sales.ss_sales_price > 3.19 and item.i_container = 'Unknown   ';
select sr_return_time_sk from store_returns, store_sales where ss_item_sk=sr_item_sk and store_sales.ss_sales_price > 7.05 and store_sales.ss_ext_discount_amt < 0.00;
select d_current_year from catalog_sales, date_dim where d_date_sk=cs_sold_date_sk and catalog_sales.cs_ship_mode_sk = 15 and catalog_sales.cs_ship_addr_sk > 4672;
select ws_ext_ship_cost from web_sales, store_sales where ws_item_sk=ss_item_sk and store_sales.ss_ticket_number = 119333 and web_sales.ws_ext_tax > 0.00;
select ws_ext_ship_cost from web_sales, web_returns where wr_order_number=ws_order_number and web_sales.ws_bill_addr_sk > 45614 and web_returns.wr_returning_addr_sk > 15553;
select cs_ship_date_sk from promotion, catalog_sales where cs_promo_sk=p_promo_sk and promotion.p_item_sk < 5038 and catalog_sales.cs_item_sk = 17637;
select cs_coupon_amt from item, catalog_sales where i_item_sk=cs_item_sk and catalog_sales.cs_ship_hdemo_sk = 2881 and catalog_sales.cs_ext_sales_price = 112.00;
select ss_sales_price from store_returns, store_sales where sr_item_sk=ss_item_sk and store_returns.sr_return_ship_cost = 2914.00 and store_sales.ss_list_price > 89.10;
select ws_ext_list_price from web_sales, web_returns where wr_order_number=ws_order_number and web_sales.ws_ext_sales_price > 5017.35 and web_sales.ws_warehouse_sk > 5;
select ws_ext_discount_amt from web_sales, date_dim where d_date_sk=ws_sold_date_sk and web_sales.ws_ship_cdemo_sk = 1101255 and web_sales.ws_web_site_sk > 13;
select cs_ext_discount_amt from catalog_sales, date_dim where d_date_sk=cs_sold_date_sk and date_dim.d_day_name = 'Tuesday  ' and catalog_sales.cs_net_paid_inc_ship > 1156.44;
select cs_ext_list_price from catalog_sales, inventory where cs_item_sk=inv_item_sk and catalog_sales.cs_coupon_amt = 212.97 and catalog_sales.cs_bill_customer_sk = 90140;
select cs_order_number from catalog_sales, date_dim where d_date_sk=cs_sold_date_sk and date_dim.d_current_day = 'N' and date_dim.d_fy_week_seq < 10082;
select cs_warehouse_sk from promotion, catalog_sales where cs_promo_sk=p_promo_sk and promotion.p_channel_dmail = 'N' and catalog_sales.cs_quantity > 55;
select sr_return_quantity from store_returns, store_sales where sr_ticket_number=ss_ticket_number and store_returns.sr_returned_date_sk > 2451326 and store_returns.sr_reason_sk < 32;
select inv_item_sk from warehouse, inventory where w_warehouse_sk=inv_warehouse_sk and inventory.inv_item_sk < 13106 and warehouse.w_street_name = 'Wilson Elm';
select cr_warehouse_sk from catalog_returns, catalog_sales where cr_order_number=cs_order_number and catalog_sales.cs_ship_hdemo_sk < 5324 and catalog_sales.cs_list_price = 37.36;
